Asistencia360-main/FrontEnd/Controllers/FAQController.cs
using FrontEnd.Helpers;
using FrontEnd.Models;
using FrontEnd.Utils;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FrontEnd.Controllers
{
    public class FAQController : Controller
    {

        FAQHelper faqHelper;

        public FAQController()
        {
            faqHelper = new FAQHelper();

        }
        public void AssignViewBag()
        {

        }

        // GET: FAQController
        public ActionResult Index()
        {
            AssignViewBag();
            return View();
        }

        public ActionResult LoadIndex(string active)
        {
            List<FAQViewModel> models = faqHelper.GetAll(active);

            var response = new DataTableResponseModel<FAQViewModel>
            {
                data = models.ToList(),
                RecordsFiltered = models.Count(),
                RecordsTotal = models.Count()
            };
            return Json(response);
        }

        // GET: FAQController/Create
        public ActionResult Create()
        {
            AssignViewBag();
            return View();
        }

        // POST: FAQController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FAQViewModel faq)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    faq.Active = true;
                    faq = faqHelper.Add(faq);
                    AssignViewBag();
                    return RedirectToAction(nameof(Index));
                }
                return View(faq);
            }
            catch
            {
                return View();
            }
        }

        // GET: FAQController/Edit/5
        public ActionResult Edit(int id)
        {
            FAQViewModel faq = faqHelper.GetByID(id);
            AssignViewBag();
            return View(faq);
        }

        // POST: FAQController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FAQViewModel faq)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    faq = faqHelper.Edit(faq);
                    AssignViewBag();
                    return RedirectToAction(nameof(Index));
                }
                return View(faq);
            }
            catch
            {
                return View();
            }
        }
        // POST: FAQController/Deactivate/5
        [HttpPost]
        public ActionResult Deactivate(int id)
        {
            faqHelper.Deactivation(id);
            AssignViewBag();
            return RedirectToAction(nameof(Index));

        }
    }
}

Asistencia360-main/FrontEnd/Controllers/RoleController.cs
using FrontEnd.Models.UserModels;
using FrontEnd.Utils;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FrontEnd.Controllers
{
    public class RoleController: Controller
    {
        // GET: RoleController
        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult LoadData()
        {
            List<RoleViewModel> models = new List<RoleViewModel>();

            models.Add(new RoleViewModel
            {
                role_id = 1,
                title = "Admin",
                description = "Usuario Administrador",
                active = true,
            });

            models.Add(new RoleViewModel
            {
                role_id = 2,
                title = "Estandar",
                description = "Usuario Estandar",
                active = true,
            });

            var reponse = new DataTableResponseModel<RoleViewModel>
            {
                data = models.ToList(),
                RecordsFiltered = models.Count(),
                RecordsTotal = models.Count()
            };

            return Json(reponse);
        }

        // GET: RoleController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: RoleController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RoleController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RoleController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RoleController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RoleController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RoleController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Asistencia360-main/FrontEnd/Controllers/TicketController.cs
using FrontEnd.Helpers;
using FrontEnd.Models;
using FrontEnd.Models.UserModels;
using FrontEnd.Utils;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Differencing;
using System.Collections.Generic;
using System.Net.Security;
using System.Net;
using System.Reflection;
using System.Security.Cryptography.X509Certificates;

namespace FrontEnd.Controllers
{
    public class TicketController: Controller
    {
        private TicketHelper ticketHelper;
        private ServiceHelper serviceHelper;
        private UserHelper userHelper;
        private InternalServiceHelper internalServiceHelper;
        private CommentHelper commentHelper;



        public TicketController()
        {
            ticketHelper = new TicketHelper (); 
            serviceHelper = new ServiceHelper ();
            userHelper = new UserHelper ();
            internalServiceHelper = new InternalServiceHelper ();
            commentHelper = new CommentHelper ();

        }

        public void AssignViewBag()
        {

        }

        // GET: TicketController
        public ActionResult Index()
        {
            AssignViewBag();
            return View();
        }

        public ActionResult LoadIndex(string active)
        {
            List<TicketViewModel> models = ticketHelper.GetAll(active);

            var response = new DataTableResponseModel<TicketViewModel>
            {
                data = models.ToList(),
                RecordsFiltered = models.Count(),
                RecordsTotal = models.Count()
            };

            return Json(response);
        }

        // GET: TicketController/Create
        public ActionResult Create()
        {

            AssignViewBag();
            return View();
        }

        // POST: TicketController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TicketViewModel ticket)
        {
            try
            {
                ModelState.Remove("FAQlist");
                ModelState.Remove("Services");
                ModelState.Remove("Technicians");
                ModelState.Remove("InventoryList");
                ModelState.Remove("InternalServices");
                ModelState.Remove("status");
                ModelState.Remove("Customers");
                ModelState.Remove("Comments");




                if (ModelState.IsValid)
                {
                    ticket.StartDate = DateTime.Now;
                    ticket.customerId = 1;
                    ticket.status = "Nuevo";
                    ticket.Type = "Sin asignar";
                    ticket = ticketHelper.Add(ticket);
                    

                    AssignViewBag();

                    return RedirectToAction(nameof(Index));

                }
                
                return View(ticket);
            }
            catch
            {
                return View();
            }
        }

        // GET: TicketController/Edit/5
        public ActionResult Edit(int id)
        {

            TicketViewModel ticket = ticketHelper.GetByID(id);
            // Obtener la lista de servicios para el desplegable

            List<ServiceViewModel> listaservicios = serviceHelper.GetServiceInfoFromAll("true");

            var combinedList = listaservicios.Select(s => new { CombinedValue = $"{s.Type}-{s.Priority}-{s.ServiceId}", s.NameType });

            ViewBag.ServiceInfoList = new SelectList(combinedList, "CombinedValue", "NameType");
           //            ViewBag.ServiceInfoList = new SelectList(listaservicios, "Type", "NameType", "Priority");
            // Cargar los comentarios asociados al ticket
            List<CommentViewModel> comentarios = ObtenerComentariosDelTicket(id);

            // Asignar los comentarios al modelo del ticket
            ticket.Comments = comentarios;

 


            AssignViewBag();
            return View(ticket);
        }

        //Metodo para tomar comentarios
        private List<CommentViewModel> ObtenerComentariosDelTicket(int ticketId)
        {
            // Usar la función definida en tu CommentHelper para obtener comentarios por ticketId
            return commentHelper.GetCommentsByTicketId(ticketId);
        }

        // POST: TicketController/Edit/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Edit(int id, TicketViewModel ticket)
        {
            try
            {             
                ticket.serviceId = ticket.serviceId.Split("-")[2];
                ticket.technicianId = 1;

                ticket = ticketHelper.Edit(ticket);

                //separar datos.

                
                AssignViewBag();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Error al editar el ticket: " + ex.Message);
                return View(ticket);
            }
        }

        // POST: TicketController/Deactivate/5
        [HttpPost]
       //[ValidateAntiForgeryToken]
        public ActionResult Deactivate(int id)
        {
            ticketHelper.Deactivation(id);         
            AssignViewBag();
            return RedirectToAction(nameof(Index));
        }


    }
}

Asistencia360-main/FrontEnd/Controllers/UserController.cs
using FrontEnd.Helpers;
using FrontEnd.Models;
using FrontEnd.Models.UserModels;
using FrontEnd.Utils;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FrontEnd.Controllers
{
    public class UserController: Controller
    {
        private CompanyHelper companyHelper;
        private DepartmentHelper departmentHelper;
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LoadData()
        {
            List<UserViewModel> models = new List<UserViewModel>();

            for (int i = 0; i < 4; i++)
            {
                models.Add(new UserViewModel
                {
                    UserId = i,
                    Name = "Juan",
                    LastName = "Pérez",
                    IdNumber = i,
                    Email = "example@example.com",
                    Password = "abc",
                    CompanyId = i,
                    DepartmentId = i,
                    RoleId = i,
                    Active = true
                });

                models.Add(new UserViewModel
                {
                    UserId = i,
                    Name = "Juan",
                    LastName = "Pérez",
                    IdNumber = i,
                    Email = "example@example.com",
                    Password = "abc",
                    CompanyId = i,
                    DepartmentId = i,
                    RoleId = i,
                    Active = true
                });

                models.Add(new UserViewModel
                {
                    UserId = i,
                    Name = "Juan",
                    LastName = "Pérez",
                    IdNumber = i,
                    Email = "example@example.com",
                    Password = "abc",
                    CompanyId = i,
                    DepartmentId = i,
                    RoleId = i,
                    Active = true
                });
            }

            var response = new DataTableResponseModel<UserViewModel>
            {
                data = models.ToList(),
                RecordsFiltered = models.Count(),
                RecordsTotal = models.Count()
            };

            return Json(response);
        }

        public ActionResult Register()
        {
            //
            //
            //Sending Companies List
            //
            List<CompanyViewModel> companies = companyHelper.GetAll("true");
            List<DepartmentViewModel> departments = departmentHelper.GetAll("true");

            //
            //Sending Departments List
            //
            

            UserViewModel user = new UserViewModel();
            user.Companies = companies;
            user.Departments = departments;

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(UserViewModel model)
        {
            try
            {
                return RedirectToAction("Index", "Dashboard");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel model)
        {
            try
            {
                return RedirectToAction("Index", "Dashboard");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Logout()
        {
            return View("Login");
        }

        public ActionResult ForgotPassword()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ForgotPassword(ForgotPasswordViewModel model)
        {
            try
            {
                TempData["ForgotPasswordSuccess"] = "Se ha enviado un correo a " + model.email + " con los pasos para restablecer la contraseña";
                return RedirectToAction("Login");
            }
            catch
            {
                return View();
            }
        }


    }
}

Asistencia360-main/FrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>DarkPanTickets</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <link href="img/favicon.ico" rel="icon">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="~/WebStyles/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/WebStyles/css/style.css" rel="stylesheet" />
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/WebStyles/js/site.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
</head>
@RenderSection("scripts", false)
<body>

    <div class="container-fluid position-relative d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-secondary navbar-dark">
                <a href=@Url.Action("Index", "Home") class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary">Asistencia360</h3>
                </a>

                <div class="navbar-nav w-100">
                    <a href=@Url.Action("Index", "Dashboard") class="nav-item nav-link"><i class="fa fa-chart-bar me-2"></i>Dashboard</a>
                    <a href=@Url.Action("Index", "Ticket") class="nav-item nav-link"><i class="fa fa-ticket-alt me-2"></i>Tiquetes</a>
                    <a href=@Url.Action("Index", "Service") class="nav-item nav-link"><i class="fa fa-desktop me-2"></i>Servicios</a>
                    <a href=@Url.Action("Index", "Inventory") class="nav-item nav-link"><i class="fa fa-boxes me-2"></i>Inventario</a>
                    <a href=@Url.Action("Index", "FAQ") class="nav-item nav-link"><i class="fa fa-question-circle me-2"></i>FAQ</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="far fa-file-alt me-2"></i>Catálogos</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href=@Url.Action("Index", "Company") class="dropdown-item">Empresas</a>
                            <a href=@Url.Action("Index", "Department") class="dropdown-item">Departamentos</a>
                            <a href=@Url.Action("Index", "InternalService") class="dropdown-item">Servicios Internos</a>
                            <a href=@Url.Action("Index", "HardDrive") class="dropdown-item">Discos Duros</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-lock me-2"></i>Seguridad</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href=@Url.Action("Index", "User") class="dropdown-item">Usuarios</a>
                            <a href=@Url.Action("Index", "Role") class="dropdown-item ">Roles</a>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->
        <!-- Content Start -->

        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
                <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-user-edit"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
                <div class="navbar-nav align-items-center ms-auto">
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-bell me-lg-2"></i>
                            <span class="d-none d-lg-inline-flex">Notificaciones</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Profile updated</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">New user added</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Password changed</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all notifications</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            @*<img class="rounded-circle me-lg-2" src="~/WebStyles/img/user.jpg" alt="" style="width: 40px; height: 40px;">*@
                            <span class="d-none d-lg-inline-flex">
                                @*@if (Session["userName"] != null)
                                {
                                    @Session["userName"].ToString()
                                }*@
                            </span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">Mi perfil</a>
                            <a href="#" class="dropdown-item">Configuracion</a>
                            <a href=@Url.Action("Logout", "User") class="dropdown-item">Salir</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->
            <!-- Blank Start -->
            @RenderBody()
            <!-- Blank End -->
            <!-- Footer Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-secondary rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                            &copy; <a href=@Url.Action("Index", "Home")>Services365</a>, All Right Reserved.
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->
        </div>
        <!-- Content End -->
        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script type="text/javascript">
        var baseUrl = "@Url.Content("~/")";
    </script>
    <script src="~/WebStyles/lib/chart/chart.min.js"></script>
    <script src="~/WebStyles/lib/easing/easing.min.js"></script>
    <script src="~/WebStyles/lib/waypoints/waypoints.min.js"></script>
    <script src="~/WebStyles/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/WebStyles/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/WebStyles/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/WebStyles/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Template Javascript -->
    <script src="~/WebStyles/js/main.js"></script>
</body>

</html>

Asistencia360-main/FrontEnd/Views/Shared/_Layout_Login.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>DarkPanTickets</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <link href="img/favicon.ico" rel="icon">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="~/WebStyles/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/WebStyles/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />
    <link href="~/WebStyles/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/WebStyles/css/style.css" rel="stylesheet">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
</head>

<body>

    <div class="container-fluid position-relative d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <!-- Sign In Start -->
        @RenderBody()

        <!-- Sign In End -->
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/WebStyles/lib/chart/chart.min.js"></script>
    <script src="~/WebStyles/lib/easing/easing.min.js"></script>
    <script src="~/WebStyles/lib/waypoints/waypoints.min.js"></script>
    <script src="~/WebStyles/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/WebStyles/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/WebStyles/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/WebStyles/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>
    <script src="~/WebStyles/js/main.js"></script>
</body>

</html>